version: '3.7'

services:

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=auth
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-compose-network
  
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=login
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-compose-network

volumes:
  mongodb-data:

networks:
  mongo-compose-network:
    driver: bridge